console.info('以下为ban.js的加载')

ServerEvents.recipes(event => {

    event.remove({ id: 'ad_astra:recipes/launch_pad' })
    event.remove({ id: 'ad_astra:recipes/nasa_workbench' })
    event.remove({ id: 'ad_astra:recipes/steel_cable' })
    event.remove({ id: 'ad_astra:recipes/desh_cable' })
    event.remove({ id: 'ad_astra:recipes/desh_fluid_pipe' })
    event.remove({ id: 'ad_astra:recipes/ostrum_fluid_pipe' })
    event.remove({ id: 'ad_astra:recipes/coal_generator' })
    event.remove({ id: 'ad_astra:recipes/compressor' })
    event.remove({ id: 'ad_astra:recipes/solar_panel' })
    event.remove({ id: 'mining_dims:mining_teleporter' })
    event.remove({ id: 'mining_dims:caving_teleporter' })
    event.remove({ id: 'mining_dims:climbing_teleporter' })
    event.remove({ id: 'mining_dims:nethering_teleporter' })
    event.remove({ id: 'mining_dims:hunting_teleporter' })
    event.remove({ id: 'ae2:network/blocks/spatial_io_pylon' })
    event.remove({ id: 'ae2:spatial_anchor' })
    event.remove({ id: 'botania:loki_ring' })
    event.remove({ id: 'botania:laputa_shard' })
    event.remove({ id: 'create:crafting/kinetics/filter' })
    event.remove({ id: 'create:crafting/appliances/filter_clear' })
    event.remove({ id: 'create:crafting/kinetics/attribute_filter' })
    event.remove({ id: 'create:crafting/appliances/attribute_filter_clear' })

})